[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  external_node_modules = [
    "puppeteer-extra", 
    "next", 
    "sharp", 
    "@ampproject/toolbox-optimizer",
  ]
[[plugins]]
  package= "netlify-plugin-chromium"
    [plugins.inputs]
      packageManager = "yarn"
      setChromePathInEnv = "true"
      failBuildOnError = "true"
